Repository AY2425S1-CS2103T-F13-4/tp, pull requests merged in 2024-10, with the labels that each got.

#52 Transaction
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Transaction.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium

#61 View transactions gui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/java/seedu/address/ui/TransactionListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#69 Delete transaction command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTransactionCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteTransactionCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.Medium

#74 Update version number
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#83 Update DG for listt
  docs/DeveloperGuide.md
  docs/diagrams/ListTransactionsActivityDiagram.puml
  docs/diagrams/ListTransactionsDiagram.puml
Labels: priority.Medium

#90 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#103 Update ModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.Low, type.Task

#122 Improve GUI
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: alpha-bug

#121 Fix transactions commands
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
  src/main/java/seedu/address/logic/commands/FindTransactionCommand.java
  src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/SummaryCommandTest.java
Labels: alpha-bug

#125 Improve find success message
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: alpha-bug

#128 Update messages
  src/main/java/seedu/address/logic/Messages.java
Labels: alpha-bug
