Repository AY2425S1-CS2103T-F13-4/tp, pull requests merged in 2024-11, with the labels that each got.

#132 Update `addt` command to not modify filtered client list
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
Labels: alpha-bug

#130 Improve `listt` messages
  src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
  src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
Labels: alpha-bug

#134 Update error messages
  src/main/java/seedu/address/logic/Messages.java
Labels: alpha-bug

#140 Update edit command to keep transactions
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: alpha-bug

#144 Transaction double
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Transaction.java
  src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: alpha-bug

#147 Update parsing for transactions
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddTransactionCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTransactionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: alpha-bug

#156 Make command words case-insensitive
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: alpha-bug

#139 Update Index.md
  docs/index.md
Labels: type.DocumentationBug

#158 Update message constraint for Transaction
  src/main/java/seedu/address/model/person/Transaction.java
Labels: alpha-bug

#165 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.Low, severity.Low, alpha-bug, type.DocumentationBug

#166 Update add for duplicate handling
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enchancement, priority.Medium, severity.Medium, alpha-bug, type.FeatureFlaw

#168 Update parsing to handle blank inputs for `addt` command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddTransactionCommandParser.java
Labels: priority.High, severity.Medium, alpha-bug, type.FunctionalityBug

#171 Update add to handle phone numbers more flexibly
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.Medium, severity.Medium, alpha-bug, type.FeatureFlaw

#172 Renamed all instances of AB3 to Clientell
  build.gradle
  docs/site.json
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.Low, severity.Low, alpha-bug

#173 Change `findt` to be used in transaction view
  src/main/java/seedu/address/logic/commands/FindTransactionCommand.java
  src/main/java/seedu/address/logic/parser/FindTransactionCommandParser.java
  src/test/java/seedu/address/logic/commands/FindTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/FindTransactionCommandParserTest.java
Labels: alpha-bug

#178 Update BetterModelClassDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
Labels: priority.Low, severity.Low, type.DocumentationBug

#176 Update error messages for `addt`
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
  src/main/java/seedu/address/model/person/Transaction.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
Labels: alpha-bug
